---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.1
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: zookeeper
    driver:
      vm_hostname: zookeeper
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[zookeeper_demo::default]

  - name: master
    driver:
      vm_hostname: master
      network:
        - ["private_network", {ip: "192.168.33.11"}]
        - ["forwarded_port", {guest: 5050, host: 5055}]
        - ["forwarded_port", {guest: 8080, host: 8088}]
    run_list:
      - recipe[mesos_demo::master]
    attributes:
