---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.1
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: zookeeper
    driver:
      vm_hostname: zookeeper
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[zookeeper_demo::default]

  - name: master
    driver:
      vm_hostname: master
      network:
        - ["private_network", {ip: "192.168.33.11"}]
    run_list:
      - recipe[mesos_demo::hostsfile]
      - recipe[mesos_demo::master]
    attributes:
      mesos_demo:
        zookeeper:
          host: 192.168.33.10
          port: 2181

  - name: slave01
    driver:
      vm_hostname: slave01
      network:
        - ["private_network", {ip: "192.168.33.12"}]
    run_list:
      - recipe[mesos_demo::hostsfile]
      - recipe[mesos_demo::slave]
    attributes:
      mesos_demo:
        zookeeper:
          host: 192.168.33.10
          port: 2181

  - name: slave02
    driver:
      vm_hostname: slave02
      network:
        - ["private_network", {ip: "192.168.33.13"}]
    run_list:
      - recipe[mesos_demo::hostsfile]
      - recipe[mesos_demo::slave]
    attributes:
      mesos_demo:
        zookeeper:
          host: 192.168.33.10
          port: 2181
