---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.1
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: node1
    driver:
      vm_hostname: node1
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[mesos_demo::default]
      - recipe[zookeeper_demo::default]
    attributes:
